light_colors = [
    "Lavender Blush",
    "Lemon Chiffon",
    "Light Blue",
    "Light Cyan",
    "Light Goldenrod",
    "Light Pink",
    "Light Salmon",
    "Light Sky Blue",
    "Light Steel Blue",
    "Light Yellow",
    "Mint Cream",
    "Misty Rose",
    "Pale Green",
    "Pale Turquoise",
    "Pale Violet Red",
    "Peach Puff",
    "Powder Blue",
    "Seashell",
    "Sky Blue",
    "Snow"
]
